### ISSUE TITLE
Documents lack key information.

### ISSUE THREAD

**Issue by assemble-engineering** [phidnhh/strapi-plugin-fast-content#2]
I have installed this plugin and it is somewhat working. 
The only usage instruction is a quickly moving carousel.
It took some time to decipher how to create a collection type, not happy about spending all that time to figure it out.
Tried the import data and no joy. I get the green success banner but... where does the data go? It's not in the new collection.
Can we get some usage documentation?

**Comment by phidn** [comment]
Sorry for the inconvenience. I made a simple video of the process.
https://www.youtube.com/watch?v=hML7eNUaiZs
